config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :recommendations
  devise_for :homes
  root 'welcome#index'
  resources :homes
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/home.rb
class Home < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recommendations

  def active_for_authentication?
   super && approved?
 end

 def inactive_message
   if !approved?
     :not_approved
   else
     super # Use whatever other message
   end
 end
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :home
  validates :industry, presence: true
  
  def self.available_industries
    return [""] unless Recommendation.first
    arr = []
    Recommendation.all.each { |r| arr << r.industry.downcase }
    arr.uniq.sort
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) << [:primary_first_name, :primary_last_name, :street_address, :primary_phone, :alt_phone, :primary_birth_day, :primary_birth_month]
    devise_parameter_sanitizer.for(:sign_up) << [:primary_first_name, :primary_last_name, :street_address, :primary_phone, :alt_phone, :primary_birth_day, :primary_birth_month]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  before_filter :set_home, only: :show
  
  def index
    @homes = Home.all
  end
  
  def show
    if params[:approved] == "false"
      @homes = Home.find_all_by_approved(false)
    else
      @homes = Home.all
    end
  end
  
private
  def set_home
    @home = Home.find(params[:id])
  end
  
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: [:show, :edit, :update, :destroy]

  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.all
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
  end

  # GET /recommendations/new
  def new
    @recommendation = Recommendation.new
  end

  # GET /recommendations/1/edit
  def edit
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    @recommendation = Recommendation.new(recommendation_params)
    @recommendation.industry = params[:new_industry] unless params[:new_industry].empty?

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully created.' }
        format.json { render :show, status: :created, location: @recommendation }
      else
        format.html { render :new }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recommendations/1
  # PATCH/PUT /recommendations/1.json
  def update
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { render :show, status: :ok, location: @recommendation }
      else
        format.html { render :edit }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to recommendations_url, notice: 'Recommendation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recommendation_params
      params.require(:recommendation).permit(:company_name, :industry, :contact_name, :address, :phone, :email, :notes, :home_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
protected
  def after_udpate_path_for(resource)
    edit_registration_path(current_home)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_home!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def avatar size
    url = [
      "http://placebear.com/#{size.to_s}/#{size.to_s}",
      "http://lorempixel.com/#{size.to_s}/#{size.to_s}/animals",
       "http://lorempixel.com/#{size.to_s}/#{size.to_s}/cats"
    ].sample
    image_tag url, alt:"avatar", class:"image-object"
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/homes/index.html.erb
<div class="col-md-6 col-md-offset-3">
  <h2>Your Neighbors</h2>
  <% @homes.each do |home| %>
  <address>
    <div class="media">
      <div class="media-left">
        <%# unless @home.avatar %>
          <%= avatar 100 %>
        <%# else %>
          <!-- avatar -->
        <%# end %>
      </div>
      <div class="media-body">
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <strong><%= home.primary_first_name %> <%= home.primary_last_name %></strong></br>
        <span class="glyphicon glyphicon-home" aria-hidden="true"></span> <%= home.street_address %></br>
        <span class="glyphicon glyphicon-phone" aria-hidden="true"></span> <%= home.primary_phone %></br>
        <span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span> <%= home.alt_phone %></br>
        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <%= mail_to home.email %></br>
      </div>
    </div>
  </address>
  
  <% end %>
</div>

app/views/homes/show.html.erb
<div class="col-md-6 col-md-offset-3">
  <h2>My Home Profile</h2>

  <% if current_home.id == @home.id %>
    <%= link_to 'Edit', edit_registration_path(current_home) %>
  <% end %>
  <h3>Primary Contact</h3>
  
  
  <div class="row">
    <div class="col-md-6">
      <address>
        <div class="media">
          <div class="media-left">
            <%# unless @home.avatar %>
              <%= avatar 100 %>
            <%# else %>
              <!-- avatar -->
            <%# end %>
          </div>
          <div class="media-body">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <strong><%= @home.primary_first_name %> <%= @home.primary_last_name %></strong></br>
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span> <%= @home.street_address %></br>
            <span class="glyphicon glyphicon-phone" aria-hidden="true"></span> <%= @home.primary_phone %></br>
            <span class="glyphicon glyphicon-phone-alt" aria-hidden="true"></span> <%= @home.alt_phone %></br>
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <%= mail_to @home.email %></br>
          </div>
        </div>
      </address>
    </div>
    <div class="col-md-6">
      <p>
        <%= link_to 'Link to Photos', '#' %> <small>coming soon</small>
      </p>
      <p>
        <%= link_to 'Link to Recommendations', '#' %> <small>coming soon</small>
      </p>
      <p>
        <%= link_to 'Link to Travel Notifications', '#' %> <small>coming soon</small>
      </p>
    </div>
  </div>
  <h3>Household <small>coming soon</small></h3>
  <% if current_home.id == @home.id %>
    <%= link_to 'Add household member', '#' %>
  <% end %>
  
  <h3>Pets <small>coming soon</small></h3>
  <% if current_home.id == @home.id %>
    <%= link_to 'Add pet', '#' %>
  <% end %>
  
  <% if current_home.admin? && current_home.id == @home.id %>
    <h3>User approval</h3>
    <table class="table">
      <% @homes.each do |home| %>
          <tr>
              <td><%= home.email %></td>
              <td><%= home.approved %></td>
          </tr>
      <% end %>
    </table>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <title>TowneyView</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">


  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Towney View", root_path, class: "navbar-brand" %>
        <!-- <a class="navbar-brand" href="#">Towney View</a> -->
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <% if home_signed_in? %>
          <ul class="nav navbar-nav">
              <li><%= link_to 'Neighbors', homes_path %></a></li>
              <li><%= link_to 'Recommendations', recommendations_path %></li>
              <li><%= link_to 'Your Home', home_path(current_home) %></li>
              <li><%= content_tag :a, "Travel", onclick: "alert('Coming Soon!');" %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li>
                <p class='navbar-text text-capitalize'>Welcome <%= current_home.primary_first_name %></p>
              </li>
              <li><%= link_to "Sign out", destroy_home_session_path, method: :delete %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign up", new_registration_path(resource_name) %></li>
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
 <div class="container-fluid">
     <%= yield %>
   </div>
  <footer>
    <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js' %>
  </footer>
</body>
</html>

app/views/recommendations/_form.html.erb
<%= form_for(@recommendation) do |f| %>
  <% if @recommendation.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      <%= pluralize(@recommendation.errors.count, "error") %> prohibited this recommendation from being saved:
      <ul>
      <% @recommendation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.hidden_field :home_id, value: current_home.id %>
  
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name, class:"form-control"%>
  </div>
  <div class="field">
    <%= f.label :industry %>
    <div id="industryList"><%= f.select :industry, Recommendation.available_industries %>
      <span id="addIndustry">
        <a href="#">Add an industry...</a>
      </span>
    </div>
    <div style="display:none" id="newIndustry">
      <span id="newIndustryField"><%= text_field_tag :new_industry, nil, class:"form-control" %></span>
      <a href="#" id="showIndustryList">Show industries...</a>
    </div>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br>
    <%= f.text_field :contact_name, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control", row:"3" %>
  </div>
  <div class="actions">
    <%= button_tag "Submit", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Editing Recommendation</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Show', @recommendation %> |
  <%= link_to 'Back', recommendations_path %>
</div>

app/views/recommendations/index.html.erb
<div class="col-md-offset-3">
  <h2>Recommended Services <br><small>Find and recommend services you like and trust</small></h1>
  <p id="notice"><%= notice %></p>
  
 
      <% @recommendations.each do |recommendation| %>
          <span><%= recommendation.company_name %></span>
          <span><%= recommendation.industry %></span>
          <span><%= recommendation.contact_name %></span>
          <span><%= recommendation.address %></span>
          <span><%= recommendation.phone %></span>
          <span><%= recommendation.email %></span>
          <span><%= link_to 'Show', recommendation %></span>
          <% if current_home.id == recommendation.home_id %>
            <span><%= link_to 'Edit', edit_recommendation_path(recommendation) %></span>
            <span><%= link_to 'Destroy', recommendation, method: :delete, data: { confirm: 'Are you sure?' } %></span>
          <% end %>
        </br>
      <% end %>
  
  <%= link_to 'New Recommendation', new_recommendation_path %>
</div>

app/views/recommendations/new.html.erb
<div class="col-md-offset-3 col-md-6">
  <h1>New Recommendation</h1>
  
  <%= render 'form' %>
  
  <%= link_to 'Back', recommendations_path %>
</div>

app/views/recommendations/show.html.erb
<div class="col-md-6 col-md-offset-3"><p id="notice"><%= notice %></p>
  
  <p>
    <strong>Company name:</strong>
    <%= @recommendation.company_name %>
  </p>
  
  <p>
    <strong>Industry:</strong>
    <%= @recommendation.industry %>
  </p>
  
  <p>
    <strong>Contact name:</strong>
    <%= @recommendation.contact_name %>
  </p>
  
  <p>
    <strong>Address:</strong>
    <%= @recommendation.address %>
  </p>
  
  <p>
    <strong>Phone:</strong>
    <%= @recommendation.phone %>
  </p>
  
  <p>
    <strong>Email:</strong>
    <%= @recommendation.email %>
  </p>
  
  <p>
    <strong>Notes:</strong>
    <%= @recommendation.notes %>
  </p>
  
  <%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
  <%= link_to 'Back', recommendations_path %>
</div>

app/views/welcome/index.html.erb
    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>Village at Towney View</h1>
            <h3>Our neighborhood resource</h3>
            <br>
            <a href="#about" class="btn btn-dark btn-lg">Find Out More</a>
        </div>
    </header>

    <!-- About -->
    <section id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>The Village at Towney View should make life easier.</h2>
                    <p class="lead">Neighborhood phone book, recommended services/contractors, and a travel alert tool.</p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- Services -->
    <!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
    <section id="services" class="services bg-primary">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-10 col-lg-offset-1">
                    <h2>Your Tools</h2>
                    <hr class="small">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                          <div class="service-item">
                              <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-group fa-stack-1x text-primary"></i>
                              </span>
                              <h4>
                                  <strong>Neighbors</strong>
                              </h4>
                              <p>See who your neighbors are and how you can reach them.</p>
                              <%= link_to 'Neighbors', homes_path, class: "btn btn-light" %>
                          </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-thumbs-o-up fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Recommendations</strong>
                                </h4>
                                <p>Recommend or find contractors and services.</p>
                                <%= link_to 'Recommendations', recommendations_path, class: "btn btn-light" %>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-paper-plane fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Travel Alert</strong>
                                </h4>
                                <p>Let your neighbors know you'll be out of town, and for how long.</p>
                                <a href="#" class="btn btn-light">Coming Soon</a>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-home fa-stack-1x text-primary"></i>
                            </span>
                                <h4>
                                    <strong>Your Home</strong>
                                </h4>
                                <p>Update your home information</p>
                              </br>
                                <%= link_to 'Your Home', home_path(current_home),  class: "btn btn-light" %>
                            </div>
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- jQuery -->
    <!-- <script src="js/jquery.js"></script> -->

    <!-- Bootstrap Core JavaScript -->
    <!-- <script src="js/bootstrap.min.js"></script> -->

    <!-- Custom Theme JavaScript -->
    <script>
        // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    </script>